routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('home');
});

Route::resource('/countries', 'CountryController');
Route::resource('/eventcategories', 'EventCategoryController');
Route::resource('/eventtopics', 'EventTopicController');

app/Country.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Country extends Model
{
    protected $table = 'countries';
}

app/Http/Controllers/CountryController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Country;

class CountryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return Response
     */
    public function index()
    {
        $countries = Country::all();
        return view('countries.index', array('countryList' =>$countries));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return Response
     */
    public function create()
    {
        $countries = Country::all();
        return view('countries.create', array('countryList' =>$countries));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'name'=>'required',
            'code'=> 'required',
        ]);
        $country = new Country;
        $country->name = $request->name;
        $country->code = $request->code;
        $country->save();
        return redirect('/countries')->with('success', 'country has been added');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return Response
     */
    public function show($id)
    {
        $country = Country::find($id);
        $countrylist = Country::all();
        
        return view('countries.show', array('country' => $country));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return Response
     */
    public function edit($id)
    {
        $country = Country::find($id);
        $countryList = Country::all();
        return view('countries.edit', compact('country', 'countryList'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([
            'name'=>'required',
            'code'=> 'required',
        ]);

        $country = Country::find($id);
        $country->name = $request->get('name');
        $country->code = $request->get('code');
     
        $country->save();

        return redirect('countries')->with('success', 'updated');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return Response
     */
    public function destroy($id)
    {
        $country = Country::find($id);
        $country->delete();
        
        return redirect('countries');
    }
}

resources/views/countries/create.blade.php
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <meta name="author" content="Timothy Van Esch">
    <link rel="stylesheet" href="{{ asset('css/fricfrac.css') }}" type="text/css"/>
    <title>Fric-Frac</title>
  </head>
  <body>
    <main>
      <article>
        <header>
          <h2>Land</h2>
          <nav>
            <a href="{{route('countries.index')}}">Annuleren</a>
          </nav>
        </header>
        <form method="post" action="{{ route('countries.store') }}">
          <div class="form-group">
            @csrf
            <label for="name">Name:</label>
            <input type="text" class="form-control" name="name"/>
          </div>
          <div class="form-group">
            <label for="code">code :</label>
            <input type="text" class="form-control" name="code"/>
          </div>
          <button type="submit" class="btn btn-primary">Add</button>
        </form>
      </article>
      @include('countries.readingAll')
  </main>
</body>
</html>

resources/views/countries/edit.blade.php
<?php //edit = updateone ?>
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <meta name="author" content="Ben Dierckx">
    <link rel="stylesheet" href="{{ asset('css/fricfrac.css') }}" type="text/css"/>
    <title>Fric-Frac</title>
  </head>
  <body>
    <main>
        <article>
          <header>
              <h2>Land</h2>
          <nav>
             <a href="{{route('countries.index')}}">Annuleren</a>
          </nav>
          </header>
          <form method="post" action="{{ route('countries.update', $country->id) }}">
              @method('PATCH')
              @csrf
              <div>
                <label for="name">Name:</label>
                <input type="text"  name="name" value="{{ $country->name }}" />
              </div>
              <div>
                <label for="code">code :</label>
                <input type="text" name="code" value="{{ $country->code }}" />
              </div>
              
              <button type="submit">Update</button>
          </form>
        </article>
        @include('countries.readingAll')
    </main>
  </body>
</html>

resources/views/countries/index.blade.php
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">
        <meta name="author" content="Timothy Van Esch">
        <link rel="stylesheet" href="{{ asset('css/fricfrac.css') }}" type="text/css"/>
        <title>Fric-Frac</title>
    </head>
    <body>
        <main>
            <article>
                <header>
                    <h2>Land</h2>
                        <nav>
                            <a href="{{route('countries.create')}}">Create</a>
                        </nav>
                </header>
                <nav>
                    <fieldset>
                        <div>
                        </div>
                    </fieldset>
                </nav>
            </article>
            @include('countries.readingAll')
        </main>
    </body>
</html>

resources/views/countries/readingAll.blade.php
<aside>
    <table>
        <thead>
            <tr>
                <td>select</td>
                <td>Name</td>
                <td>Code</td>
            </tr>
        </thead>
        <tbody>
            @foreach($countryList as $country) 
            <tr>
                <td><a href="{{ route('countries.show',$country->id)}}">show</a></td>
                <td>{{$country->name}}</td>
                <td>{{$country->code}}</td>
            </tr>
            @endforeach
        </tbody>
    </table>
</aside>

resources/views/countries/show.blade.php
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <meta name="author" content="Timothy Van Esch">
    <link rel="stylesheet" href="{{ asset('css/fricfrac.css') }}" type="text/css"/>
    <title>Fric-Frac</title>
  </head>
  <body>
    <main>
      <article>
        <header>
    			<h2>Land</h2>
    			<nav>
    				<a href="{{route('countries.edit', ['id' => $country->id])}}">Edit</a>
    				<a href="{{route('countries.create')}}">Create</a>
    				<button type="submit" value="delete" form="form">Delete</button>
    				<a href="{{route('countries.index')}}">Annuleren</a>
    			</nav>
    		</header>
        <form action="{{ route('countries.destroy', ['id' => $country->id])}}" id="form" method="post">
          @csrf
          @method('DELETE')
    			<div>
    				<label for="Name">Naam</label>
    				<input type="text" readonly id="Name" name="name" value="{{$country->name}}">
    			</div>
    			<div>
    				<label for="Code">Code</label>
    				<input type="text" readonly id="Code" name="countryCode" value="{{$country->code}}">
    			</div>
        </form>
        <a href={{route('countries.index')}}>index</a>
      </article>
    </main>
  </body>
</html>