routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('home');
});

Route::resource('/countries', 'CountryController');
Route::resource('/eventcategories', 'EventCategoryController');
Route::resource('/eventtopics', 'EventTopicController');

app/EventTopic.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class EventTopic extends Model
{
    protected $table = 'event_topics';
}

app/Http/Controllers/EventTopicController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\EventTopic;

class EventTopicController extends Controller
{
     /**
     * Display a listing of the resource.
     *
     * @return Response
     */
    public function index()
    {
        $eventtopics = EventTopic::all();
        return view('eventtopics.index', array('eventtopicsList' =>$eventtopics));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return Response
     */
    public function create()
    {
        $eventtopics = EventTopic::all();
        return view('eventtopics.create', array('eventtopicsList' =>$eventtopics));
    }

   /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'name'=>'required',
        ]);
        $eventtopics = new EventTopic;
        $eventtopics->name = $request->name;
        $eventtopics->save();
        return redirect('/eventtopics')->with('success', 'eventtopic has been added');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return Response
     */
    public function show($id)
    {
        $eventtopics = EventTopic::find($id);
        $eventtopicsList = EventTopic::all();
        
        return view('eventtopics.show', array('eventtopic' => $eventtopics));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return Response
     */
    public function edit($id)
    {
        $eventtopics = EventTopic::find($id);
        $eventtopicsList = EventTopic::all();
        return view('eventtopics.edit', compact('eventtopics', 'eventtopicsList'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([
            'name'=>'required',
        ]);

        $eventtopics = EventTopic::find($id);
        $eventtopics->name = $request->get('name');
     
        $eventtopics->save();

        return redirect('eventtopics')->with('success', 'updated');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return Response
     */
    public function destroy($id)
    {
        $eventtopics = EventTopic::find($id);
        $eventtopics->delete();
        
        return redirect('eventtopics');
    }
}

resources/views/eventtopics/create.blade.php
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">
        <meta name="author" content="Timothy Van Esch">
        <link rel="stylesheet" href="{{ asset('css/fricfrac.css') }}" type="text/css"/>
        <title>Fric-Frac</title>
    </head>
    <body>
        <main>
            <article>
                <header>
                    <h2>EventTopic</h2>
                    <nav>
                        <button type="submit" value="insert" form="form">Insert</button>
                        <a href="{{route('eventtopics.index')}}">Annuleren</a>
                    </nav>
                </header>
                <form method="post" action="{{ route('eventtopics.store') }}">
                    @csrf
   				<div>
   					<label for="Name">Naam</label>
   					<input type="text" id="Name" name="name">
   				</div>
                    <button type="submit" class="btn btn-primary">Add</button>
                </form>
            </article>
            @include('eventtopics.readingall')
        </main>
</body>
</html>

resources/views/eventtopics/edit.blade.php
<?php //edit = updateone ?>
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <meta name="author" content="Timothy Van Esch">
    <link rel="stylesheet" href="{{ asset('css/fricfrac.css') }}" type="text/css"/>
    <title>Fric-Frac</title>
  </head>
  <body>
    <main>
        <article>
          <header>
              <h2>EventTopic</h2>
          <nav>
             <a href="{{route('eventCategories.index')}}">Annuleren</a>
          </nav>
          </header>
          <form method="post" action="{{ route('eventCategories.update', $eventCategory->id) }}">
              @method('PATCH')
              @csrf
              <div>
                <label for="name">Name:</label>
                <input type="text"  name="name" value="{{ $eventCategory->name }}" />
              </div>
              
              <button type="submit">Update</button>
          </form>
        </article>
        @include('eventCategories.readingAll')
    </main>
  </body>
</html>

resources/views/eventtopics/index.blade.php
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">
        <meta name="author" content="Timothy Van Esch">
        <link rel="stylesheet" href="{{ asset('css/fricfrac.css') }}" type="text/css"/>
        <title>Fric-Frac</title>
    </head>
    <body>
<main>
    <article>
        <header>
            <h2>EventTopic</h2>
                <nav>
                    <a href="{{route('eventtopics.create')}}">Insert</a>
                </nav>
        </header>
        <nav>
            <fieldset>
                <div>
                </div>
            </fieldset>
        </nav>
    </article>
    @include('eventtopics.readingAll')
</main>
    </body>

resources/views/eventtopics/readingAll.blade.php
<aside>
    <table>
        <thead>
            <tr>
                <td>select</td>
                <td>Name</td>
            </tr>
        </thead>
        <tbody>
            @foreach($eventtopicsList as $eventtopic) 
            <tr>
                <td><a href="{{ route('eventtopics.show',$eventtopic->id)}}">show</a></td>
                <td>{{$eventtopic->name}}</td>
            </tr>
            @endforeach
        </tbody>
    </table>
</aside>

resources/views/eventtopics/show.blade.php
<?php //edit = updateone ?>
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">
        <meta name="author" content="Timothy Van Esch">
        <link rel="stylesheet" href="{{ asset('css/fricfrac.css') }}" type="text/css"/>
        <title>Fric-Frac</title>
     </head>
  <body>
    <main>
      <article>
        <header>
    			<h2>EventTopic</h2>
    			<nav>
    				<a href="{{route('eventtopics.edit', ['id' => $eventtopic->id])}}">Edit</a>
    				<a href="{{route('eventtopics.create')}}">Create</a>
    				<button type="submit" value="delete" form="form">Delete</button>
    				<a href="{{route('eventtopics.index')}}">Annuleren</a>
    			</nav>
    		</header>
        <form action="{{ route('eventtopics.destroy', ['id' => $eventtopic->id])}}" id="form" method="post">
          @csrf
          @method('DELETE')
    			<div>
    				<label for="Name">Naam</label>
    				<input type="text" readonly id="Name" name="name" value="{{$eventtopic->name}}">
    			</div>
        </form>
        <a href={{route('eventtopics.index')}}>index</a>
      </article>
    </main>
  </body>
</html>