routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('home');
});

Route::resource('/countries', 'CountryController');
Route::resource('/eventcategories', 'EventCategoryController');
Route::resource('/eventtopics', 'EventTopicController');

app/EventCategory.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class EventCategory extends Model
{
    protected $table = 'event_categories';
}

app/Http/Controllers/EventCategoryController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\EventCategory;

class EventCategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $eventcategories = EventCategory::all();
        return view('eventcategories.index', array('eventcategoryList' =>$eventcategories));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $eventcategories = EventCategory::all();
        return view('eventcategories.create', array('eventcategoryList' =>$eventcategories));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'name'=>'required',
        ]);
        $eventcategory = new EventCategory;
        $eventcategory->name = $request->name;
        $eventcategory->save();
        return redirect('/eventcategories')->with('success', 'eventcategory has been added');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $eventcategory = EventCategory::find($id);
        $eventcategoryList = EventCategory::all();
        
        return view('eventcategories.show', array('eventcategory' => $eventcategory));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $eventcategory = EventCategory::find($id);
        $eventcategoryList = EventCategory::all();
        return view('eventcategories.edit', compact('eventcategory', 'eventcategoryList'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([
            'name'=>'required',
        ]);

        $eventcategory = EventCategory::find($id);
        $eventcategory->name = $request->get('name');
     
        $eventcategory->save();

        return redirect('eventcategories')->with('success', 'updated');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $eventcategory = EventCategory::find($id);
        $eventcategory->delete();
        
        return redirect('eventcategories');
    }
}

resources/views/eventcategories/create.blade.php
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">
        <meta name="author" content="Timothy Van Esch">
        <link rel="stylesheet" href="{{ asset('css/fricfrac.css') }}" type="text/css"/>
        <title>Fric-Frac</title>
    </head>
    <body>
        <main>
          <article>
            <header>
              <h2>EventCategory</h2>
              <nav>
                <a href="{{route('eventcategories.index')}}">Annuleren</a>
              </nav>
            </header>
            <form method="post" action="{{ route('eventcategories.store') }}">
              <div class="form-group">
                @csrf
                <label for="name">Name:</label>
                <input type="text" class="form-control" name="name"/>
              </div>
              <button type="submit" class="btn btn-primary">Add</button>
            </form>
          </article>
          @include('eventcategories.readingAll')
      </main>
    </body>
    </html>

resources/views/eventcategories/edit.blade.php
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">
        <meta name="author" content="Timothy Van Esch">
        <link rel="stylesheet" href="{{ asset('css/fricfrac.css') }}" type="text/css"/>
        <title>Fric-Frac</title>
    </head>
    <body>
        <main>
            <article>
              <header>
                  <h2>EventCategory</h2>
              <nav>
                 <a href="{{route('eventcategories.index')}}">Annuleren</a>
              </nav>
              </header>
              <form method="post" action="{{ route('eventcategories.update', $eventcategory->id) }}">
                  @method('PATCH')
                  @csrf
                  <div>
                    <label for="name">Name:</label>
                    <input type="text"  name="name" value="{{ $eventcategory->name }}" />
                  </div>
                  
                  <button type="submit">Update</button>
              </form>
            </article>
            @include('eventcategories.readingAll')
        </main>
      </body>
    </html>

resources/views/eventcategories/index.blade.php
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">
        <meta name="author" content="Timothy Van Esch">
        <link rel="stylesheet" href="{{ asset('css/fricfrac.css') }}" type="text/css"/>
        <title>Fric-Frac</title>
    </head>
    <body>
        <main>
            <article>
                <header>
                    <h2>EventCategory</h2>
                        <nav>
                            <a href="{{route('eventcategories.create')}}">Create</a>
                        </nav>
                </header>
                <nav>
                    <fieldset>
                        <div>
                        </div>
                    </fieldset>
                </nav>
            </article>
            @include('eventcategories.readingAll')
        </main>
    </body>
</html>

resources/views/eventcategories/readingAll.blade.php
<aside>
    <table>
        <thead>
            <tr>
                <td>select</td>
                <td>Name</td>
            </tr>
        </thead>
        <tbody>
            @foreach($eventcategoryList as $eventcategory) 
            <tr>
                <td><a href="{{ route('eventcategories.show',$eventcategory->id)}}">show</a></td>
                <td>{{$eventcategory->name}}</td>
            </tr>
            @endforeach
        </tbody>
    </table>
</aside>

resources/views/eventcategories/show.blade.php
<?php //edit = updateone ?>
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">
        <meta name="author" content="Timothy Van Esch">
        <link rel="stylesheet" href="{{ asset('css/fricfrac.css') }}" type="text/css"/>
        <title>Fric-Frac</title>
    </head>
    <body>
        <main>
          <article>
            <header>
                    <h2>EventCategory</h2>
                    <nav>
                        <a href="{{route('eventcategories.edit', ['id' => $eventcategory->id])}}">Edit</a>
                        <a href="{{route('eventcategories.create')}}">Create</a>
                        <button type="submit" value="delete" form="form">Delete</button>
                        <a href="{{route('eventcategories.index')}}">Annuleren</a>
                    </nav>
                </header>
            <form action="{{ route('eventcategories.destroy', ['id' => $eventcategory->id])}}" id="form" method="post">
              @csrf
              @method('DELETE')
                    <div>
                        <label for="Name">Naam</label>
                        <input type="text" readonly id="Name" name="name" value="{{$eventcategory->name}}">
                    </div>
            </form>
            <a href={{route('eventcategories.index')}}>index</a>
          </article>
        </main>
      </body>
    </html>